name: Deploy Postgres script
run-name: Setting up new postgres database

on: [push]

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: Test Output
        run: echo "This is a test."

  connect-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show databases
        run: |
          psql -h "${{ secrets.DB_HOSTNAME }}" \
               -p 5432 \
               -U "${{ secrets.DB_USER }}" \
               -d postgres \
               -c "SELECT datname FROM pg_database;"
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run SQL file
        run: |
          psql -h "${{ secrets.DB_HOSTNAME }}" \
               -p 5432 \
               -U "${{ secrets.DB_USER }}" \
               -d "${{ secrets.DB_NAME }}" \
               -f "Create_gisdb.sql"
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
